name = "MPILarge"
uuid = "03b5a6d4-3f85-4eec-9d38-a1f1826bd98e"
version = "0.1.0"
authors = ["Andreas Feuerpfeil <development@manybodylab.com>"]

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[compat]
MPI = "0.20.23"
julia = "1.10"
